<?php


namespace App\Models\Traits;

use \Ramsey\Uuid\Uuid as RamseyUuid;

trait Uuid
{
    protected static function boot() //TODO: Change the autogenerated stub
    {
        parent::boot();
        static::creating(function($obj){
            $obj->id = RamseyUuid::uuid4();
        });
    }
}
